version: '3.3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'olx-app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'B0813aran()16'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'B0813aran()16'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/data/

  server:
    build: 
      context: .
      dockerfile: DockerFileServer
    ports:
      - 3000:3000
    volumes:
      - ./server:/data/
      - ./node_modules
    #depends_on: 
    #  - server-database

    ##added
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports: 
      - "80:80"
    volumes: 
      - ./client:/data/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - client